window.usersData = [
    {
        "id": 1,
        "name": "диспрозия",
        "role": "Владелец",
        "desc": "Владелец листа.<br>вход бесплатно / галочка 50 звезд /",
        "fullDesc": "Создатель данного проекта. Занимаюсь управлением и развитием.",
        "tg": "@vkwebint",
        "channel": "https://t.me/vkwebint",
        "img": "https://i.postimg.cc/bwW2Gbxj/disprozia.jpg",
        "verified": true,
        "pinned": true,
        "isScam": false,
        "skills": "Управление, создание проектов",
        "regDate": "01 сентября 2023 г.",
        "activity": "Постоянная"
    },
    {
        "id": 2,
        "name": "Six Seven",
        "role": "Кодеры",
        "desc": "Gifts / @AVAYNIN",
        "fullDesc": "Gifts",
        "tg": "@AVAYNIN",
        "channel": "https://t.me/giftsitg",
        "img": "https://i.postimg.cc/nh1283BJ/Six-Seven.jpg",
        "verified": true,
        "pinned": false,
        "isScam": false,
        "skills": "Кодер",
        "regDate": "13 сентября 2026 г.",
        "activity": "Постоянная"
    },
    {
        "id": 3,
        "name": "Fkrpl",
        "role": "Кодеры",
        "desc": "Ky",
        "fullDesc": "Ky",
        "tg": "@Fkrpl",
        "channel": "https://t.me/botgfts",
        "img": "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=",
        "verified": true,
        "pinned": false,
        "isScam": false,
        "skills": "Кодер",
        "regDate": "13 сентября 2026 г.",
        "activity": "Постоянная"
    },
    {
        "id": 4,
        "name": "каиро revs 62+",
        "role": "Скам",
        "desc": "",
        "fullDesc": "Д",
        "tg": "@dev_kairo",
        "channel": "",
        "img": "https://i.postimg.cc/brHDGBzT/pidoras.jpg",
        "verified": false,
        "pinned": false,
        "isScam": true,
        "skills": "Скам",
        "regDate": "13 сентября 2026 г.",
        "activity": "Низкая"
    },
    {
        "id": 5,
        "name": "диспрозия",
        "role": "Осинтеры",
        "desc": "пришел в сферу в 2022, начал увлекаться Osint с 2023-2024, имел 3 проекта от 100-200 сабов",
        "fullDesc": "пришел в сферу в 2022, начал увлекаться Osint с 2023-2024, имел 3 проекта от 100-200 сабов",
        "tg": "@vkwebint",
        "channel": "",
        "img": "https://i.postimg.cc/CL93F3Sv/disprozia.jpg",
        "verified": true,
        "pinned": true,
        "isScam": false,
        "skills": "Осинтеры",
        "regDate": "13 сентября 2026 г.",
        "activity": "Постоянная"
    },
    {
        "id": 6,
        "name": "Виолетта маниачка",
        "role": "Средний фейм",
        "desc": "Привет, я Deanoner, владелец проекта Cyber Scout. Проект появился в 2017 году, сейчас занимаюсь OSINT (сбор и анализ открытых данных).",
        "fullDesc": "Привет, я Deanoner, владелец проекта Cyber Scout. Проект появился в 2017 году, сейчас занимаюсь OSINT (сбор и анализ открытых данных).",
        "tg": "@cmcnx",
        "channel": "",
        "img": "https://i.postimg.cc/DZDKfFJ1/IMG-20260914-114551-818.jpg",
        "verified": false,
        "pinned": false,
        "isScam": false,
        "skills": "Средний фейм",
        "regDate": "13 сентября 2026 г.",
        "activity": "Постоянная"
    }
];
